---
title: "Human monocyte gene set enrichment analysis (GSEA)"
author: "Laura Blanton"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_knit$set(root.dir = "") #set root directory
```

####Load data
```{r}
library(dplyr)
library(fgsea)
library(data.table)
library(ggplot2)
myPath <- #set path here

#Load autosomal gene responses to Xi and Chr Y dosage
monocyte.Xresponse <- read.table(paste0(myPath,"/sca-immune/Autosomal_linear_regressions/monocyte/monocyte_autosomal_Xresponse.txt", header = T, sep = "\t"))
monocyte.Yresponse <- read.table(paste0(myPath,"/sca-immune/Autosomal_linear_regressions/monocyte/monocyte_autosomal_Yresponse.txt", header = T, sep = "\t"))
monocyte.Xresponse.Yabsent <- read.table(paste0(myPath,"/sca-immune/Autosomal_linear_regressions/monocyte/monocyte_autosomal_Yabsent_Xresponse.txt", header = T, sep = "\t"))
monocyte.Yresponse.Ypresent <- read.table(paste0(myPath,"/sca-immune/Autosomal_linear_regressions/monocyte/monocyte_autosomal_Ypresent_Yresponse.txt", header = T, sep = "\t"))
monocyte.Xresponse.1Y <- read.table(paste0(myPath,"/sca-immune/Autosomal_linear_regressions/monocyte/monocyte_autosomal_1Y_Xresponse.txt", header = T, sep = "\t"))


#load Hallmark gene sets from MSigDB (https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#H) 
hallmark_geneSet <- gmtPathways(paste0(myPath, "/sca-immune/Gene_set_enrichment/h.all.v7.1.symbols.gmt"))

```

##Gene set enrichment for full models
```{r}
#Gene set enrichment for the Xi response in full model
Xranks <- monocyte.Xresponse$stat
names(Xranks) <- monocyte.Xresponse$Gene
Xranks <- na.omit(Xranks)

fgseaRes_Xhallmark <- fgsea(pathways = hallmark_geneSet, stats = Xranks, minSize = 15, maxSize = 20000)
fwrite(fgseaRes_Xhallmark, file="fgseaRes_monocyte_Xresponse_tstat_hallmark.txt", sep="\t", sep2=c("", " ", ""))

#Gene set enrichment for the Chr Y response in full model
Yranks <- monocyte.Yresponse$stat
names(Yranks) <- monocyte.Yresponse$Gene
Yranks <- na.omit(Yranks)

fgseaRes_Yhallmark <- fgsea(pathways = hallmark_geneSet, stats = Yranks, minSize = 15, maxSize = 20000)
fwrite(fgseaRes_Yhallmark, file="fgseaRes_monocyte_Yresponse_tstat_hallmark.txt", sep="\t", sep2=c("", " ", ""))

```
#Gene set enrichment for subset models
```{r}
#Gene set enrichment for the Xi response in subset model with no Y karyotypes (X, XX, XXX)
Xranks.Yabsent <- monocyte.Xresponse.Yabsent$stat
names(Xranks.Yabsent) <- monocyte.Xresponse.Yabsent$Gene
Xranks.Yabsent <- na.omit(Xranks.Yabsent)

fgseaRes_X.Yabsent.hallmark <- fgsea(pathways = hallmark_geneSet, stats = Xranks.Yabsent, minSize = 15, maxSize = 20000)
fwrite(fgseaRes_X.Yabsent.hallmark, file="fgseaRes_monocyte_Xresponse.Yabsent_tstat_hallmark.txt", sep="\t", sep2=c("", " ", ""))

#Gene set enrichment for the Chr Y response in subset model with >1 Chr Y karyotypes (XY, XXY, XYY)
Yranks.Ypresent <- monocyte.Yresponse.Ypresent$stat
names(Yranks.Ypresent) <- monocyte.Yresponse.Ypresent$Gene
Yranks.Ypresent <- na.omit(Yranks.Ypresent)

fgseaRes_Y.Ypresent.hallmark <- fgsea(pathways = hallmark_geneSet, stats = Yranks.Ypresent, minSize = 15, maxSize = 20000)
fwrite(fgseaRes_Y.Ypresent.hallmark, file="fgseaRes_monocyte_Yresponse.Ypresent_tstat_hallmark.txt", sep="\t", sep2=c("", " ", ""))

#Gene set enrichment for the Xi response in subset model with only 1 Chr Y (XY vs. XXY)
Xranks.1Y <- monocyte.Xresponse.1Y$stat
names(Xranks.1Y) <- monocyte.Xresponse.1Y$Gene
Xranks.1Y <- na.omit(Xranks.1Y)

fgseaRes_X.1Y.hallmark <- fgsea(pathways = hallmark_geneSet, stats = Xranks.1Y, minSize = 15, maxSize = 20000)
fwrite(fgseaRes_X.1Y.hallmark, file="fgseaRes_monocyte_Xresponse.1Y_tstat_hallmark.txt", sep="\t", sep2=c("", " ", ""))


```
#Compare NES across models
```{r}
monocyte.allmodels <- list(fgseaRes_Xhallmark, fgseaRes_X.Yabsent.hallmark,fgseaRes_X.1Y.hallmark, fgseaRes_Yhallmark,  fgseaRes_Y.Ypresent.hallmark)
monocyte.fullmodels <- list(fgseaRes_Xhallmark, fgseaRes_Yhallmark)

monocyte.allmodels <- monocyte.allmodels %>% reduce(full_join, by = 'pathway')
monocyte.allmodels.nes <- monocyte.allmodels[, c("pathway", "NES.x", "NES.y", "NES.x.x", "NES.y.y", "NES")]
colnames(monocyte.allmodels.nes) <- c("pathway", "Full model", "Subset: no Chr Y", "Subset: 1 Chr Y", "Full model", "Subset: >1 Chr Y")
rownames(monocyte.allmodels.nes) <- monocyte.allmodels.nes$pathway
monocyte.allmodels.nes <- monocyte.allmodels.nes[,-1]

monocyte.allmodels.padj <- monocyte.allmodels[, c("pathway", "padj.x", "padj.y", "padj.x.x", "padj.y.y", "padj")]
colnames(monocyte.allmodels.padj) <-c("pathway", "Full model", "Subset: no Chr Y", "Subset: 1 Chr Y", "Full model", "Subset: >1 Chr Y")
rownames(monocyte.allmodels.padj) <- monocyte.allmodels.padj$pathway
monocyte.allmodels.padj <- monocyte.allmodels.padj[,-1]

library(ComplexHeatmap)
library(circlize)
#all models
col_fun = colorRamp2(c(-2.5, 0, 2.5), c("#1E8BE5", "white", "#EFC036"))
col_fun(seq(-2.5, 2.5))
pdf(file = "monocyte_all_pathways_NES_heatmap.pdf", width = 7, height = 9)
Heatmap(monocyte.allmodels.nes, column_title = "Monocyte", col = col_fun, column_names_rot = 45, cluster_columns = FALSE, cell_fun = function(j, i, x, y, w, h, fill) {
    if(monocyte.allmodels.padj[i, j] < 0.001) {
        grid.text("***", x, y)
    } else if(monocyte.allmodels.padj[i, j] < 0.01) {
        grid.text("**", x, y)
    } else if(monocyte.allmodels.padj[i, j] < 0.05) {
        grid.text("*", x, y)
    }
})
dev.off()




```


